version: '3'
services:
  web:
    image: tamatan/apache-php-centos7
#    build:
#      context: .
    container_name: "web"
    ports:
      - "80:80"
    volumes:
      - "./html:/var/www/html"

  portainer:
    image: portainer/portainer-ce
    container_name: "portainer"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


