version: '3'
services:
  lamp:
    build:
      context: .
    container_name: "lamp"
    ports:
      - "80:80"
    volumes:
      - "./html:/var/www/html"

  portainer:
    image: portainer/portainer-ce
    container_name: "portainer"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


