version: '3'
services:
#  apache-php-centos7:
#    image: tamatan/apache-php-centos7
##    build:
##      context: .
#    container_name: "apache-php-centos7"
#    ports:
#      - "80:80"
#    volumes:
#      - "./html:/var/www/html"
  web:
    build:
      context: .
    container_name: "web"
    ports:
      - "80:80"
    volumes:
      - "./html:/var/www/html"


  portainer:
    image: portainer/portainer-ce
    container_name: "portainer"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


